# Site settings
title: James Peret Blog
email: james.peret@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a hacker from São Paulo, Brazil. Currently working on Avalanche Network as the main programmer and designer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamesperet.com.br" # the base hostname & protocol for your site
twitter_username: jamesperet
github_username:  jamesperet

# Build settings
markdown: kramdown
